Data Loading

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from data import clean_data

df = clean_data()
df.head(3)

c:\Users\sahil\OneDrive\Documents\Data_Analytics\Amazon_analysis\data.py:7: DtypeWarning: Columns (23) have mixed types. Specify dtype option on import or set low_memory=False.
  temp_df = pd.read_csv(r"C:\Users\sahil\Downloads\Sales_Dataset\Amazon Sale Report.csv")
c:\Users\sahil\OneDrive\Documents\Data_Analytics\Amazon_analysis\data.py:16: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df['date'] = pd.to_datetime(df['date'],errors='coerce')
c:\Users\sahil\OneDrive\Documents\Data_Analytics\Amazon_analysis\data.py:7: DtypeWarning: Columns (23) have mixed types. Specify dtype option on import or set low_memory=False.
  temp_df = pd.read_csv(r"C:\Users\sahil\Downloads\Sales_Dataset\Amazon Sale Report.csv")
c:\Users\sahil\OneDrive\Documents\Data_Analytics\Amazon_analysis\data.py:16: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df['date'] = pd.to_datetime(df['date'],errors='coerce')

,order_id,date,status,fulfilment,sales_channel,ship-service-level,style,sku,category,size,...,ship-city,ship-state,ship-postal-code,ship-country,promotion-ids,b2b,fulfilled-by,month,year,revenue
0,405-8078784-5731545,2022-04-30,Cancelled,Merchant,Amazon.in,Standard,SET389,SET389-KR-NP-S,Set,S,...,MUMBAI,MAHARASHTRA,400081.0,IN,NaN,False,Easy Ship,4,2022,0.0
1,171-9198151-1101146,2022-04-30,Shipped - Delivered to Buyer,Merchant,Amazon.in,Standard,JNE3781,JNE3781-KR-XXXL,kurta,3XL,...,BENGALURU,KARNATAKA,560085.0,IN,Amazon PLCC Free-Financing Universal Merchant ...,False,Easy Ship,4,2022,406.0
2,404-0687676-7273146,2022-04-30,Shipped,Amazon,Amazon.in,Expedited,JNE3371,JNE3371-KR-XL,kurta,XL,...,NAVI MUMBAI,MAHARASHTRA,410210.0,IN,IN Core Free Shipping 2015/04/08 23-48-5-108,True,NaN,4,2022,329.0

In [2]:
df.isnull().sum()

order_id                  0
date                      0
status                    0
fulfilment                0
sales_channel             0
ship-service-level        0
style                     0
sku                       0
category                  0
size                      0
asin                      0
courier_status         6872
qty                       0
currency               7795
amount                 7795
ship-city                33
ship-state               33
ship-postal-code         33
ship-country             33
promotion-ids         49153
b2b                       0
fulfilled-by          89698
month                     0
year                      0
revenue                7795
dtype: int64

Droping Missing Values and Column

In [3]:
# Drop critical missing values
df = df.dropna(subset=['amount'])

# Fix revenue
df['revenue'] = df['amount']

# Fill categorical missing values
df['courier_status'] = df['courier_status'].fillna('Unknown')
df['currency'] = df['currency'].fillna('INR')
df['promotion-ids'] = df['promotion-ids'].fillna('No Promotion')

# Fill location
df['ship-city'] = df['ship-city'].fillna('Unknown')
df['ship-state'] = df['ship-state'].fillna('Unknown')
df['ship-postal-code'] = df['ship-postal-code'].fillna('Unknown')
df['ship-country'] = df['ship-country'].fillna('Unknown')

# Drop weak column
df = df.drop(columns=['fulfilled-by'])

In [4]:
df.shape
df.describe()

,date,qty,amount,month,year,revenue
count,121180,121180.000000,121180.000000,121180.000000,121180.0,121180.000000
mean,2022-05-12 12:08:14.814325760,0.961231,648.561465,4.909407,2022.0,648.561465
min,2022-03-31 00:00:00,0.000000,0.000000,3.000000,2022.0,0.000000
25%,2022-04-20 00:00:00,1.000000,449.000000,4.000000,2022.0,449.000000
50%,2022-05-10 00:00:00,1.000000,605.000000,5.000000,2022.0,605.000000
75%,2022-06-04 00:00:00,1.000000,788.000000,6.000000,2022.0,788.000000
max,2022-06-29 00:00:00,8.000000,5584.000000,6.000000,2022.0,5584.000000
std,NaN,0.214354,281.211687,0.818261,0.0,281.211687

In [5]:
df['category'].value_counts().head(10)

category
Set              47042
kurta            46717
Western Dress    14704
Top              10165
Ethnic Dress      1093
Blouse             881
Bottom             420
Saree              155
Dupatta              3
Name: count, dtype: int64

In [6]:
df = df[(df['qty'] > 0) & (df['amount'] > 0)]
df.describe()

,date,qty,amount,month,year,revenue
count,113701,113701.000000,113701.000000,113701.00000,113701.0,113701.000000
mean,2022-05-12 13:11:30.706326528,1.003852,663.164845,4.91154,2022.0,663.164845
min,2022-03-31 00:00:00,1.000000,199.000000,3.00000,2022.0,199.000000
25%,2022-04-20 00:00:00,1.000000,459.000000,4.00000,2022.0,459.000000
50%,2022-05-10 00:00:00,1.000000,625.000000,5.00000,2022.0,625.000000
75%,2022-06-04 00:00:00,1.000000,788.000000,6.00000,2022.0,788.000000
max,2022-06-29 00:00:00,8.000000,5584.000000,6.00000,2022.0,5584.000000
std,NaN,0.073385,269.538074,0.81866,0.0,269.538074

In [7]:
df["status"].value_counts()

status
Shipped                          76078
Shipped - Delivered to Buyer     28045
Cancelled                         5630
Shipped - Returned to Seller      1899
Shipped - Picked Up                945
Pending                            639
Pending - Waiting for Pick Up      272
Shipped - Returning to Seller      143
Shipped - Out for Delivery          35
Shipped - Rejected by Buyer         11
Shipped - Lost in Transit            3
Shipped - Damaged                    1
Name: count, dtype: int64

In [ ]:
df.to_csv(r"C:\Users\sahil\OneDrive\Documents\cleaned_amazon_sales.csv", index=False)

In [9]:
sample_df = df.sample(10000, random_state=42)

sample_df.to_csv("sample_amazon_sales.csv", index=False)